.gitignore, Classes/Hook/SitemapIndexHook.php
- add .gitignore for IDEs
- use constants in metaseo/Classes/Hook/SitemapIndexHook.php
=> add .gitignore, use constants in metaseo/Classes/Hook/SitemapIndexHook.php

Classes/Controller/BackendPageSeoController.php, Classes/Page/Part/MetatagPart.php, Classes/Sitemap/Generator/XmlGenerator.php
Fixed typos and variable visibility
Fixes #76
=> Visiblity of variable in MetatagPart changed, typos fixed

Configuration/TypoScript/setup.txt
=> [TASK] unblock sysext assets

Resources/Private/Layouts/BackendPageSeo.html, Resources/Private/Layouts/BackendSitemap.html
=> [BUGFIX] fix errors MetaSeo.overview.conf/MetaSeo.sitemap.conf undefined

Documentation/Constants/Index.rst, Documentation/DeveloperManual/Index.rst, Documentation/Index.rst, README.md
=> [TASK] make use of https for TYPO3 infrastructure

Documentation/Settings.yml
See https://docs.typo3.org/typo3cms/extensions/sphinx/WritersManual/DocsTypo3Org/Index.html#docs-typo3-org-edit-github
Fixes #128
=> [TASK] cross-link documentation to github repository

Documentation/Settings.yml, Documentation/_make/readme.txt
=> [BUGFIX] correct extension key for pdf rendering

Resources/Public/Backend/JavaScript/MetaSeo.overview.js
=> [BUGFIX] Show up "No page selected" when a non-page is active

Classes/Controller/AbstractAjaxController.php, Classes/Controller/Ajax/AbstractPageSeoController.php, Classes/Controller/Ajax/PageSeo/AdvancedController.php, Classes/Controller/Ajax/PageSeo/PageTitleSimController.php, Classes/Controller/Ajax/PageSeo/UrlController.php, Classes/Controller/Ajax/SitemapController.php, Classes/Exception/Ajax/AjaxException.php, Tests/Unit/Controller/Ajax/PageSeo/MetaDataControllerTest.php, Tests/Unit/Utility/DatabaseUtilityTest.php
=> [TASK] Throw AjaxExceptions directly, add tests

README.md, ext_emconf.php
=>  [TASK] Bump target version of TYPO3 CMS

Classes/Page/Part/MetatagPart.php
=> [BUGFIX] Fixing parameters in cObjGetSingle call

Resources/Private/Templates/PageParts/ServicePiwik.html
=> [TASK] Piwik: Protocol relative URL in tracking code

Resources/Public/Frontend/JavaScript/GoogleAnalyticsTrackDownload.js
=> [TASK] Refactor function names to metaSeo prefix

Classes/Sitemap/Generator/XmlGenerator.php, Configuration/TCA/tx_metaseo_setting_root.php, Resources/Private/Language/TCA/de.locallang.xlf, Resources/Private/Language/TCA/locallang.xlf, class.ext_update.php, ext_tables.sql
=> [TASK] rename table column (priorty -> priority)

Classes/Page/Part/MetatagPart.php
With current usage it's $this->pageRecord in both cases.
Fixes #99
=> [TASK] use $pageRecord from parameter

Classes/Page/Part/MetatagPart.php
=> [BUGFIX] Usper-specified canonical URL not in html output

Resources/Public/Backend/JavaScript/MetaSeo.overview.js
=> [BUGFIX] Make edit button functional for overlay classes

Configuration/TypoScript/constants.txt, Documentation/Constants/Index.rst
=> [FEATURE] Disable linkGeneration by default

Configuration/TCA/Overrides/pages.php, Configuration/TCA/Overrides/pages_language_overlay.php
=> [TASK] remove deprecated parameter $addTofeInterface

Classes/Backend/Module/AbstractModule.php, Classes/Hook/HttpHook.php, Classes/Hook/SitemapIndexHook.php, Classes/Page/Part/FooterPart.php, Classes/Scheduler/Task/AbstractTask.php, Classes/Utility/GeneralUtility.php
=> [TASK] Import namespaces

Classes/Utility/SitemapUtility.php
=> [BUGFIX] Clean handling of empty list of sitemaps

Classes/Connector.php, Classes/Page/Part/MetatagPart.php
=>  [BUGFIX] Override OpenGraph meta tags via Connector

Classes/Controller/BackendPageSeoController.php, Classes/Controller/BackendSitemapController.php, Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
* Requires TYPO3 6.2.x or TYPO3 7.6.11+
Fixes #257
=>  [BUGFIX] Bring back the country flags in 7.6

Classes/Utility/GeneralUtility.php, Documentation/Introduction/Index.rst
=> [BUGFIX] Missing arguments after signal slot dispatching

Classes/Controller/Ajax/AbstractPageSeoController.php
* Allows non-admin users to edit fields they have access to
Fixes #261
=> [BUGFIX] Fixing checking for table permissions in backend module

Classes/Page/Part/MetatagPart.php, Documentation/Introduction/Index.rst
* canonical field from page properties is
now formatted to a URL
Fixes #203
=> [BUGFIX] Fixed canonical tag generation

Classes/Page/Part/MetatagPart.php, Configuration/TypoScript/setup.txt
=> [BUGFIX] let start sectionlink be the first entry of a group

Classes/Page/Part/MetatagPart.php
=> [BUGFIX] allow metaValue to be checked for null

README.md
* Tell contributors to add themselves to the list of contributors
* mention packagist
* overall, improve the readme
Fixes #282
=> [TASK] update readme

Classes/Hook/SitemapIndexHook.php
=> [BUGFIX] Index root pages also when absRefPrefix is set

Resources/Public/Backend/Css/Default.css
=> [BUGFIX] css: dateselector not visible

Resources/Private/Templates/PageParts/ServiceGoogleAnalytics.html
* Raw filter only replaces one value, therefore we need two
Fixes #124
=> [BUGFIX] Replace GA cookieDomain

ISSUE_TEMPLATE.md, README.md
=> [TASK] Add issue template

ISSUE_TEMPLATE.md
=> [TASK] extend issue template

Classes/Controller/Ajax/AbstractPageSeoController.php, Classes/Controller/Ajax/PageSeo/MetaDataController.php, Classes/Controller/BackendPageSeoController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Public/Backend/JavaScript/MetaSeo.overview.js, Tests/Unit/Controller/Ajax/AbstractPageSeoControllerTest.php
=> [BUGFIX] CamelCase field 'lastUpdated'

Classes/Utility/SitemapUtility.php
=> [BUGFIX] Indexing: Blacklist page type 3 (external link)

Classes/Controller/Ajax/PageSeo/UrlController.php
=> [BUGFIX] URL index action: Only query existing attributes

ext_emconf.php
=> [BUGFIX] Fix autoloading via ext_emconf.php

Classes/Page/Part/MetatagPart.php
Fixes #122
Fixes #3
Fixes #235
=> [Bugfix] work around missing translations when fluidpages is used

Classes/Controller/Ajax/PageSeo/UrlController.php
=> [BUGFIX] Ajax: Translate URL simulation

Classes/Dao/PageSeoDao.php, Documentation/Introduction/Index.rst
* Makes that deleted entries in pages_language_overlay
are ignored
Fixes #333
=> [BUGFIX] Ajax: Processing deleted entries for language overlay

Documentation/AdministratorManual/Index.rst, Documentation/Constants/Index.rst, Documentation/FaqManual/Index.rst
- Fix dead links
- Fix redirects
- Use code tags where possible
Fixes #341
=> [TASK] Documentation: Fix links and redirects

Documentation/DeveloperManual/Index.rst
Fixes #345
Added an example for a simple signal implementation
=> Added signal example

Classes/Connector.php
=> [BUGFIX] Connector: Fix typo: $GLOBAL -> $GLOBALS

Classes/DependencyInjection/Utility/FrontendUtility.php, Classes/Page/RobotsTxtPage.php
=> [TASK] respect case-sensitivity for function typoLink_URL()

Documentation/Introduction/Index.rst, ext_tables.php
=> [BUGFIX] Use FontAwesome image as main module icon

Classes/Sitemap/Generator/XmlGenerator.php, Configuration/TypoScript/constants.txt, Configuration/TypoScript/setup.txt, Documentation/Constants/Index.rst, Documentation/Introduction/Index.rst
=> [FEATURE] Make priority and lastmod tag optional in sitemap

Documentation/TestingManual/Index.rst
=> [TASK] Documentation: beautify bullets

Classes/Hook/TCA/RobotsTxtDefault.php
=> [FEATURE] 8LTS: Remove unsupported setBackPath method

Resources/Private/Templates/BackendSitemap/Main.html
Fixes #377
#	Classes/Controller/BackendSitemapController.php
=> [FEATURE] Replace unsupported be.buttons.icon viewhelper

Resources/Private/Templates/BackendControlCenter/Main.html
=> Replace icon span with core.icon viewhelper

Resources/Private/Layouts/BackendPageSeo.html, Resources/Private/Layouts/BackendSitemap.html, Resources/Private/Layouts/BackendStandard.html
... instead of the rusty 'DocumentTemplate'
Fixes #391
=> [FEATURE] Use Fluid based 'ModuleTemplate'

Resources/Private/Templates/BackendControlCenter/Main.html, Resources/Private/Templates/BackendSitemap/Main.html
=> [TASK] CSS: Use bootstrap classes for tables

Classes/Controller/AbstractAjaxController.php, Classes/Controller/Ajax/AbstractPageSeoController.php, Classes/Controller/Ajax/AbstractPageSeoSimController.php, Classes/Controller/Ajax/SitemapController.php
=> [FEATURE] 8LTS/PSR-7: Use ServerResponseInterface injected by TYPO3

Classes/Hook/TCA/RobotsTxtDefault.php, Classes/Utility/FrontendUtility.php
* Using TimeTracker instead which is disabled via constructor
Fixes #403
=> [FEATURE] 8LTS/PSR-7: NullTimeTracker is deprecated

Configuration/TCA/tx_metaseo_setting_root.php
=> [FEATURE] 8LTS/TCA: showItem migrated

Configuration/tx_metaseo_setting_root.php, ext_tables.php
=> [FEATURE] 8LTS/TCA: Don't touch TCA from ext_tables.php

Documentation/AdministratorManual/Index.rst
=> [TASK] Documentation: Migrations

Classes/Page/Part/MetatagPart.php
* use common method instead
Fixes #437
=> [FEATURE] 8LTS: wrapper method HMENU was removed in 8.0

Configuration/tx_metaseo_setting_root.php, ext_tables.php
* backport from 3.0.0-dev
02e8905f6eb40cc21318160df73ac12eda69e997
Fixes #423
=> [TASK] 8LTS/TCA: Don't touch TCA from ext_tables.php

Tests/Unit/Controller/Ajax/AbstractPageSeoControllerTest.php, Tests/Unit/Utility/DatabaseUtilityTest.php
=> [FEATURE] 8LTS: Class UnitTestCase moved to TestingFramework namespace

Classes/Hook/TCA/RobotsTxtDefault.php
=> [BUGFIX] Allow arbitrary URL manipulation dynamically for RobotsTxt

Classes/Controller/Ajax/PageSeo/PageTitleController.php
=> [BUGFIX] Narrow output of pagetitle controller and pagetitlesim contr.

Classes/Page/Part/PagetitlePart.php
* reverse order to traverse root line
* consider prefix and suffix independently
Fixes #57
=> [BUGFIX] fix title inheritance

Classes/Backend/Module/AbstractModule.php, Classes/Controller/Ajax/PageSeo/MetaDataController.php, Classes/Controller/BackendControlCenterController.php, Classes/Controller/BackendRootSettingsController.php, Classes/Controller/BackendSitemapController.php, Classes/Dao/PageSeoDao.php, Classes/Page/Part/MetatagPart.php, Classes/Utility/SitemapUtility.php
=> [TASK] remove obsolete unset statements

Configuration/TCA/Overrides/sys_template.php, ext_tables.php
=> [Feature] Move addStaticFile to TCA/Overrides/sys_template.php

Classes/Utility/FrontendUtility.php
=> [FEATURE] 8LTS: Replace deprecated TSFE->anchorPrefix

Tests/Unit/Controller/Ajax/AbstractPageSeoControllerTest.php
*  also for recently merged new features
Issue #428
=> [FEATURE] 8LTS: Fix deprecated getMock()

README.md
=> [TASK] Apply new branching concept
