- Resources/Private/Templates/PageParts/ServicePiwik.html
Use // instead of http:// for the piwik counter pixel. That's the way the original piwik tracking code is doing it.
> [BUGFIX] #30 piwik: avoid mixed content for counter pixel

- Classes/Backend/Ajax/PageAjax.php
- Classes/Controller/BackendPageSeoController.php
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
Hey,
I needed recursive editing of blacklisted pages (On big pagetrees this comes very handy if you don't want specific subtrees to appear in the sitemap). So I added a button to edit fields recursively to the SEO/Metatags backend-plugin.
Maybe you're interested in that feature.
Kind Regards,
Yannick
> added recursive field editing in Backen Page/SEO module

- Configuration/TCA/Overrides/pages.php
- Configuration/TCA/Overrides/pages_language_overlay.php
of script=path/to/script.php in TCA. Makes the pages backend form work in TYPO3 7.4.
> Change wizard registration to reflect deprecation

- Classes/Backend/Module/AbstractModule.php
- Classes/Controller/BackendControlCenterController.php
- Classes/Controller/BackendPageSeoController.php
- Classes/Controller/BackendRootSettingsController.php
- Classes/Controller/BackendSitemapController.php
- Classes/Hook/TCA/RobotsTxtDefault.php
- Classes/Utility/BackendUtility.php
- Configuration/TCA/MetaseoSettingRoot.php
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
- Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
- ext_localconf.php
- ext_tables.php
* Add CSRF protection and refactoring steps (deprecation/breaking changes)
* Add compatibilty fixes for the backend of 7.5.0-dev. Status: backend is fully functional.
* Changes should be compatible to 6.2.14.
> [BUGFIX][FEATURE] use CSRF for Ajax, add compatibility fixes for 7.5.0-dev 

- Classes/Backend/Ajax/PageAjax.php
- Classes/Controller/AbstractAjaxController.php
- Classes/Controller/Ajax/AbstractPageSeoController.php
- Classes/Controller/Ajax/PageSeo/AdvancedController.php
- Classes/Controller/Ajax/PageSeo/GeoController.php
- Classes/Controller/Ajax/PageSeo/MetaDataController.php
- Classes/Controller/Ajax/PageSeo/PageTitleController.php
- Classes/Controller/Ajax/PageSeo/PageTitleSimController.php
- Classes/Controller/Ajax/PageSeo/SearchEnginesController.php
- Classes/Controller/Ajax/PageSeo/UrlController.php
- Classes/Controller/Ajax/PageSeoInterface.php
- Classes/Controller/Ajax/PageSeoSimulateInterface.php
- Classes/Controller/Ajax/SitemapController.php
- Classes/Controller/BackendPageSeoController.php
- Classes/Controller/BackendSitemapController.php
- Classes/Exception/Ajax/AjaxException.php
- Classes/Utility/BackendUtility.php
- Classes/Utility/ExtensionManagementUtility.php
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
- Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
- ext_tables.php
[TASK] OOP: Refactor Ajax controllers
* OOP: Use Subclasses for PageSeo Ajax Controllers #160 
* ExceptionHandler in Ajax Methods #161
* Use constants for Ajax controller names #159
* Use reflections to determine Ajax actions #155
* Unregister advanced Ajax controller #158
* Move Ajax classes to Controller namespace #156
Fixes #160
Fixes #159
Fixes #158
Fixes #161
Fixes #155
Fixes #156
> [TASK] OOP: Refactor Ajax controllers

- Classes/Controller/AbstractAjaxController.php
- Classes/Controller/Ajax/AbstractPageSeoController.php
- Classes/Controller/Ajax/PageSeo/PageTitleSimController.php
- Classes/Controller/Ajax/PageSeo/UrlController.php
- Classes/Controller/Ajax/PageSeoInterface.php
- Classes/Controller/Ajax/PageSeoSimulateInterface.php
- Classes/Controller/Ajax/SitemapController.php
- Classes/Controller/BackendPageSeoController.php
- Classes/Controller/BackendSitemapController.php
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
- Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
- Tests/Unit/Controller/Ajax/PageSeo/MetaDataControllerTest.php
* Remove obsolete CSRF protection (it's already provided by the core using Ajax eIDs)
* Update Interfaces for AjaxRequestHandler injection 
* Make use of the AjaxRequestHandler object for rendering
* Also render Errors via AjaxRequestHandler, including core errors
* Render arrays in json with self-provided http status codes (the core only knows status code 500).
* Test of index function call
Fixes #113
> Removes obsolete CSRF protection and makes use of core's PSR-7

- Resources/Public/Backend/JavaScript/MetaSeo.js
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
- Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
* Introduces compatibility layer for frequent deprecations
which happened in the last time
* Fixes Deprecation-62893 in 7.0
* Fixes deprecation via Feature 66047 in 7.2
* Now flash messages should work for 6.2 - 7.5-dev
Fixes #168
>  [BUGFIX] Compatibility layer for deprecation of flash messages

- Resources/Private/Templates/PageParts/ServiceGoogleAnalytics.html
- Resources/Private/Templates/PageParts/ServicePiwik.html
* Removed semicolon from fluid filter tag
* Removed spaces around comparison operators
* Use raw filter for Javascript for analytics services
* Reformat code
Fixes #179
>  [BUGFIX] Fix fluid parse error in GA javascript

- Classes/Frontend/Controller/BackendCompliantTsfeController.php
- Classes/Utility/FrontendUtility.php
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
- Resources/Public/Backend/JavaScript/MetaSeo.sitemap.js
- ext_localconf.php
* Introduces BackendCompliantTsfeController which replaces TYPO3's
TypoScriptFrontendController for the Backend via XCLASSes
* Uses http header HTTP_X_TX_METASEO_AJAX in Ajax requests to indicate
that the BackendCompliantTsfeController has to be used
* Fakes to TSFE controller that all pages have default scheme set in
page properties
* Thereby suppresses that TypoScriptFrontendController sends http
redirects when a page with scheme enforcement is processed
* Allows to toggle between enabled and disabled headers suppression
via setIsAjaxCall function (defaults to enabled)
* Requires no changes at all in existing code
Fixes #210
> [BUGFIX] Mitigate browsers to block mixed content for ajax requests

- Classes/Controller/AbstractAjaxController.php
- Documentation/Introduction/Index.rst
This prevents errors if HTTP header size exceeds max header size. If a lot
of data has to be send within an Ajax response this error will occur if
the response is send within X-JSON header.
Since CONTENT_FORMAT_JSON with value 'json' sends the response within
HTTP header (using X-JSON header) the response data is sent twice.
Changing CONTENT_FORMAT_JSON to 'jsonbody' only the HTTP response body
will contain the response data and header size will not exceed limits.
Fixes  #233
> Use HTTP body for Ajax JSON responses instead of http-headers

- Tests/Unit/Utility/DatabaseUtilityTest.php
This Bugfix mitigates a testsuite error which occurs when using PHP7:
"Metaseo\Metaseo\Utility\DatabaseUtility::conditionIn()
must be of the type array, string given"
This error did not exist in PHP 5.6
Fixes  #249
> [BUGFIX] PHP7: Fix testsuite type error

- Resources/Private/Templates/PageParts/ServiceGoogleAnalytics.html
It seems to be very important that configuration of analytics (in particular **ga('set', 'anonymizeIp', true)**) is set before **ga('send', 'pageview')** is performed.
https://www.datenschutzbeauftragter-info.de/fachbeitraege/google-analytics-datenschutzkonform-einsetzen/
https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization
https://support.google.com/analytics/answer/2763052?hl=en
> Datenschutzkonformer Tracking-Code

- Classes/Page/Part/MetatagPart.php
* Affects multiple meta tags, including copyright
Fixes #295
> [BUGFIX] Marker not replaced when at beginning of string

- Classes/Page/Part/MetatagPart.php
* No use for undefined variable
* Not beneficial in function/loop
* Dangerous because of 'by reference'
* Still replaces markers without the unset
Issue #295
Related #167
> [TASK] Markers: Remove obsolete unset()

- ext_emconf.php
* Autoload section in ext_emconf.php got introduced
with TYPO3 CMS 7.5
* It's an equivalent to composer's autoload section
(which we use for a long time), just that it's for
non-composer installs
* As of 7.6, autoloading was already working for
non-composer installs. That said, this change is not
a bug fix.
Fixes  #312
> [TASK] ext_emconf.php: Add autoload section

- Classes/Hook/SitemapIndexHook.php
Fixes #127
Fixes #forge-61858
This is cherry-picking a703006a5198639643ed4d849f886e1eaf6abe00 into metaseo 2.0.x
> [BUGFIX] Disable indexing if page is excluded from search engines

- Classes/Controller/Ajax/AbstractPageSeoController.php
* Now simulates titles also for hidden pages
* Also does not show title of parent page when page is hidden
Fixes #93
> [BUGFIX] Enable preview mode in pagetitle simulator

- Configuration/TCA/Overrides/pages.php
* Using select fields without the "renderType" setting is deprecated
in table "pages" and column "tx_metaseo_inheritance"
* Using select fields without the "renderType" setting is deprecated
in table "pages" and column "tx_metaseo_change_frequency"
Fixes #326
> Select fields without "renderType" are deprecated in table "pages"

- Classes/Dao/PageSeoDao.php
Wenn eine gelöschte language overlay row in db vorhanden ist wird immer diese verarbeitet.
Im Frontend erscheint deshalb nicht das richtige Browsertitle weil das richtige (nicht gelöschte) language overlay row in db wird nie verarbeitet.
> Language overlay bugfix

- Classes/Hook/SitemapIndexHook.php
When $absRefPrefixLength is stored between function calls, generation
of links to the root page "/" cause it to decrease, thereby surviving
function calls. When $absRefPrefixLength gets smaller than 0,
subsequent URLs are changed when saving them to the sitemap table,
or they are not saved at all.
Fixes #357
> [Bugfix] Fix that URLs get shortened in the sitemap

- Classes/Controller/BackendPageSeoController.php
- Classes/Controller/BackendSitemapController.php
- Resources/Private/Layouts/BackendPageSeo.html
- Resources/Private/Layouts/BackendSitemap.html
- Resources/Private/Layouts/BackendStandard.html
* IconUtility was removed in 8 LTS
* Remove renderMode attribute from flashmessage tags
Fixes #381
Fixes #222
> [FEATURE] 8LTS-compat: Use IconFactory instead of IconUtility

- Classes/Controller/AbstractAjaxController.php
- Classes/Controller/Ajax/AbstractPageSeoController.php
- Classes/Controller/Ajax/AbstractPageSeoSimController.php
- Classes/Controller/Ajax/PageSeoInterface.php
- Classes/Controller/Ajax/PageSeoSimulateInterface.php
- Classes/Controller/Ajax/SitemapController.php
- Classes/Controller/Ajax/SitemapInterface.php
- Classes/Utility/ExtensionManagementUtility.php
- Configuration/Backend/AjaxRoutes.php
- ext_tables.php
* not using deprecated BackendUtility::getAjaxUrl() any more
* now using ResponseInterface
* ServerRequestInterface is still unused, added it just for
the correct function signature (preliminary for issue #209)
* Adopted interfaces accordingly
* Adopted exception handling accordingly
Fixes #396
Fixes #397
> [FEATURE] 8LTS/PSR-7: Register Ajax controllers via routes

- Classes/Controller/Ajax/PageSeo/UrlController.php
- Classes/Controller/BackendPageSeoController.php
- Classes/Page/Part/MetatagPart.php
- Resources/Public/Backend/JavaScript/MetaSeo.overview.js
* disable dealing with removed attribute pages.url_scheme (in 8 LTS)
* installing extension compatibility7 gives back the old behaviour
Canonical tag: Users are highly encouraged to use the
canonicalUrl.fallbackProtocol TS variable
Fixes #411
> [FEATURE] 8LTS: transitioning from disabled pages.url_scheme

- Classes/Page/Part/MetatagPart.php
- Configuration/TCA/Overrides/pages.php
- Configuration/TCA/Overrides/pages_language_overlay.php
- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
- Resources/Private/Language/TCA/de.locallang.xlf
- Resources/Private/Language/TCA/locallang.xlf
- ext_tables.sql
Add dedicated image field for OpenGraph to pages and pages_language_overlay tables. Add support for rendering nested TypoScript/OpenGraph configuration (e.g. og:image:width).
Closes #172
> [FEATURE] Add image to OpenGraph tags

- Classes/Controller/Ajax/AbstractPageSeoController.php
- Classes/Dao/PageSeoDao.php
- Configuration/TypoScript/constants.txt
- Configuration/TypoScript/setup.txt
- Documentation/Constants/Index.rst
- Documentation/Introduction/Index.rst
- Tests/Unit/Controller/Ajax/AbstractPageSeoControllerTest.php
* defaults to doktypes 1 or 4
* allows to add more doktypes via TypoScript configuration
variable extensibility.allowedDoktypes
* changes to PageSeoDao to use this simple configuration
instead of the hard coded preset
Fixes #231
> [FEATURE] Make metaseo compatible to custom page types

- Configuration/TypoScript/setup.txt
in setup.txt,
* reset the nav_title in section links or link meta to fix meta tags
pointing always to the root page when nav_title is set
Fixes #443
> [BUGFIX] linkGeneration always set to the root page when using nav_title

- Configuration/TypoScript/setup.txt
* As of breaking change 72424, additionalHeaders must be used
together with subproperties.
Fixes #478
> [FEATURE] 8LTS: Use subproperties for additionalHeaders
